# Self-energy generated by the cubic vertex H₃. Entering at second order in
# perturbation theory, it shifts magnon energies at the same O(1/s) as the
# mean-field decoupling of H₄ in StaticCorrections.jl and must be included
# alongside it, but unlike those corrections it is frequency dependent and
# complex, its imaginary part describing decay into the two-magnon continuum.
# Conventions are collected in Corrections.jl.
#
# The end of this file assembles the full one-loop self-energy: `OneLoop` holds
# what is common to all 𝐪, and `SelfEnergy` the static and cubic parts at one 𝐪,
# as the Dyson equation of CorrectedIntensities.jl uses them.
#
# Both channels there come from one contraction of H₃ at the momenta (𝐩, 𝐤-𝐩,
# -𝐤). The third slot carries the Nambu index L+n, creating the external magnon
# of band n at 𝐤; the first two carry indices a, b over the full Nambu space
# and so describe both internal lines at once. Writing ε_𝐩 for the 2L energies
# from `bogoliubov!`, an index a ≤ L selects a forward-propagating line of
# energy ε_𝐩[a] > 0 while a > L selects a backward one, of energy -ε_𝐩[a] > 0.
# The denominator ω - ε_𝐩[a] - ε_{𝐤-𝐩}[b] is therefore the decay denominator
# in the first case and the source denominator in the second, the only remaining
# distinction between the channels being the sign of their contribution. Lines
# propagating in opposite directions belong to no one-loop diagram.
#
# The overall factor of 18 arises as (1/2)·6², where 6 = 3! converts the
# slot-symmetrized `vertex!` output into the vertices Γ₁ and Γ₂ of
# Corrections.jl and the 1/2 counts the ways of attaching the internal lines.
#
# More generally the third slot may carry any Nambu index, giving a matrix
# self-energy whose off-diagonal elements within a block mix degenerate bands
# and correct spectral weights, and whose anomalous blocks describe the
# admixture of three magnons into the ground state. Writing m̄ = mod1(m+L, 2L)
# for the index that creates what m destroys,
#
#     Σ̂[m, m′] = τ₃[m] Σ_{a,b} ±18 conj(U[a, b, m̄]) U[a, b, m̄′] / (ω - ε_𝐩[a] - ε_{𝐤-𝐩}[b]).
#
# The asymmetry between the external legs is only apparent: the leading τ₃ makes
# τ₃Σ̂ Hermitian below the three-magnon threshold, as the Dyson equation
# requires. Both this structure and the factor of 18 are verified against the
# exact Nambu Green function of a cluster, whose 𝐪-independence lets one grid
# point integrate the loop exactly.

"""
    cubic_self_energy(swt::SpinWaveTheory, qpts, energies; η, grid, vacuum=MagnonVacuum(swt))

Nambu matrix self-energy ``Σ̂_{mm′}(𝐪, ω)`` generated by the cubic term of the
Holstein-Primakoff expansion alone, evaluated at each of the given `energies`.
Returns an array of size `(2L, 2L, length(energies), size(qpts.qs)...)`, where
`L = nbands(swt)`, in the convention of the derivation at the head of
SelfEnergy.jl. See the single-argument method below for the meaning of `η` and
`grid`. The internal lines are the quasi-particles of `vacuum`, harmonic by
default, which is also the basis of the external legs. For the complete static
and cubic self-energy, oriented as the Dyson equation of
[`corrected_intensities`](@ref) uses it, see [`SelfEnergy`](@ref).
"""
function cubic_self_energy(swt::SpinWaveTheory, qpts, energies; η, grid, vacuum=MagnonVacuum(swt))
    check_corrections_supported(swt)
    η > 0 || error("Broadening η must be positive")

    L = nbands(swt)
    qpts = convert(AbstractQPoints, qpts)
    terms3 = cubic_monomials(swt)

    ret = zeros(ComplexF64, 2L, 2L, length(energies), length(qpts.qs))
    for (iq, q) in enumerate(qpts.qs)
        k = to_reshaped_rlu(swt.sys, q)
        ret[:, :, :, iq] = cubic_self_energy_at(vacuum, terms3, k, energies .+ im*η, loop_wavevectors(grid, k), η)
    end

    return reshape(ret, 2L, 2L, length(energies), size(qpts.qs)...)
end

"""
    cubic_self_energy(swt::SpinWaveTheory, qpts; η, grid, vacuum=MagnonVacuum(swt))

On-shell self-energy of each magnon due to the cubic term of the
Holstein-Primakoff expansion, ``Σ_n(𝐪, ε_{𝐪n})``, where ``ε`` are the energies
of the quasi-particles of `vacuum`, by default the [`dispersion`](@ref) of
linear spin wave theory. Returns an array of complex
numbers with the same shape as `dispersion(swt, qpts)`. The real part is a
correction to the magnon energy of relative order ``1/s``, and should be added
to the mean-field corrections of [`hartree_fock_correction`](@ref) and
[`tadpole_correction`](@ref), which enter at the same order. Minus the imaginary
part is the half-width of the magnon peak, arising from decay into the
two-magnon continuum, which [`corrected_intensities`](@ref) resolves.

In `:dipole` and `:dipole_uncorrected` modes the self-energy vanishes
identically for a collinear magnetic structure. That is special to those modes,
and does not carry over to `:SUN`, where a single-ion level may decay into two
magnons of different flavors even when every dipole is parallel. It is otherwise
given by an integral over the magnetic Brillouin zone, which is performed on a
uniform `grid` of the given dimensions. Unlike the smooth integrands elsewhere
in this module, this one is singular wherever a magnon is degenerate with a pair
of magnons, so it is regularized by a small positive broadening `η`, and both
parameters must be converged together: `η` must exceed the grid spacing of the
energies being integrated, while remaining small compared to the linewidths
themselves.

The real part converges much more readily than the imaginary one, being a
principal value. Taking `η` below the energy grid spacing makes the imaginary
part far too small, because the sampled wavevectors then miss the resonant
surface entirely. A width that halves when `η` does is such an artifact.

Because only the diagonal part of the self-energy is returned, the result is
unreliable where two bands are degenerate.
"""
function cubic_self_energy(swt::SpinWaveTheory, qpts; η, grid, vacuum=MagnonVacuum(swt))
    check_corrections_supported(swt)
    η > 0 || error("Broadening η must be positive")

    L = nbands(swt)
    qpts = convert(AbstractQPoints, qpts)
    terms3 = cubic_monomials(swt)
    H = zeros(ComplexF64, 2L, 2L)
    ws = BogoliubovWorkspace(L)

    ret = zeros(ComplexF64, L, length(qpts.qs))
    for (iq, q) in enumerate(qpts.qs)
        # Each band is evaluated at its own frequency, so the matrices for all L
        # frequencies are built and only their diagonals are kept.
        k = to_reshaped_rlu(swt.sys, q)
        ωs = vacuum_bogoliubov!(ws, H, vacuum, k)[1:L]
        Σ = cubic_self_energy_at(vacuum, terms3, k, ωs .+ im*η, loop_wavevectors(grid, k), η)
        view(ret, :, iq) .= [Σ[n, n, n] for n in 1:L]
    end

    return reshape(ret, L, size(qpts.qs)...)
end

# Calls `f(a, b, w, u, x, T1, T2)` for each pair of internal magnon lines
# belonging to a one-loop diagram, line a carrying wavevector 𝐩 and line b
# carrying 𝐤-𝐩, with `w` the multiplicity `foreach_magnon_pair` supplies,
# averaged by the caller over the loop wavevectors of `grid`. Here `u[m] = U[a,
# b, nambu_conj(m, L)]` is the external leg of band m, for m up to `M`, and `x`
# is the pair energy. Both consumers below share this scaffolding, the external
# leg being delicate.
#
# That leg is independent of the loop wavevector. Indexing its slot by
# `nambu_conj(m, L)` asks for the operator adjoint to the mode m that the Dyson
# equation propagates, and an independent `bogoliubov!` at -k supplies that only
# up to a phase per band, nothing tying the eigenvectors of one call to those of
# another. Use instead the exact Nambu symmetry P H(k)ᵗ P = H(-k), where P is
# the index swap a ↦ nambu_conj(a, L), which follows from H22(k) = H11(-k)ᵗ and
# H12(k) = H12(-k)ᵗ. That makes T3 = P conj(T(k)) P para-unitary and a
# diagonalizer of H(-k), and its column `nambu_conj(m, L)` is by construction
# the adjoint of column m of T(k). A phase left free here would rescale the
# off-diagonal elements of Σ̂ relative to the mean fields and to the observables
# of Observables.jl, which are expressed in the columns of T(k) themselves;
# degenerate bands fare worse still, two calls being free to choose different
# bases within a degenerate block.
function foreach_cubic_line(f, vac::MagnonVacuum, terms3, k, grid::LoopGrid, M)
    L = nbands(vac.swt)
    U = zeros(ComplexF64, 2L, 2L, 2L)
    scratch = similar(U)
    u = zeros(ComplexF64, M)
    T3 = zeros(ComplexF64, 2L, 2L)

    let ws = BogoliubovWorkspace(L)
        vacuum_bogoliubov!(ws, zeros(ComplexF64, 2L, 2L), vac, k)
        for b in 1:2L, a in 1:2L
            T3[a, b] = conj(ws.T[nambu_conj(a, L), nambu_conj(b, L)])
        end
    end

    foreach_magnon_pair(vac, k, grid) do p, w, T1, T2, ε1, ε2
        vertex!(U, terms3, (p, k - p, -k), (T1, T2, T3), scratch)
        for a in 1:2L, b in 1:2L
            # Internal lines must propagate in the same direction
            (a > L) == (b > L) || continue
            for m in 1:M
                u[m] = U[a, b, nambu_conj(m, L)]
            end
            f(a, b, w, u, ε1[a] + ε2[b], T1, T2)
        end
    end
end

# Nambu self-energy Σ̂(z) of the cubic vertex at wavevector `k` and each of the
# complex frequencies `zs`, as a `2L×2L×length(zs)` array. It is the Cauchy
# transform of the binned measures of `pair_measures`, oriented there to contract
# as w' G w and so related to Σ̂ by the metric and a transpose. The bins are
# sparse, so a width far below η costs nothing, and makes the binning error
# O((Δ/η)²) negligible.
function cubic_self_energy_at(vac::MagnonVacuum, terms3, k, zs, grid::LoopGrid, η)
    L = nbands(vac.swt)
    τ₃ = Diagonal([ones(L); -ones(L)])
    (; decay, source) = pair_measures(vac, terms3, k, grid; bin_width=1e-3η, words2=Vector{BosonMonomial{2}}[])
    K = cauchy_transform((decay, source), zs)
    return stack(τ₃ * transpose(view(K, :, :, iz)) for iz in eachindex(zs))
end

# Binned measures of the auxiliary model of Corrections.jl, one per channel. Each
# internal line pair contributes the mass ±y y† at pair energy x, with
#
#     y = [√18 u; β],
#
# u the external legs over all 2L Nambu indices and β the amplitudes for the
# observables (words `words2`) to create the same pair directly. The decay
# channel has x > 0 and a plus sign; the source channel x < 0 and a minus sign.
# Their Cauchy transforms, summed, give the cubic self-energy in the `[1:2L,
# 1:2L]` block, in the orientation that contracts as w' G w.
function pair_measures(vac::MagnonVacuum, terms3, k, grid::LoopGrid; bin_width, words2)
    L = nbands(vac.swt)
    Nobs = length(words2)
    decay = PairMeasure(bin_width, 2L + Nobs)
    source = PairMeasure(bin_width, 2L + Nobs)
    y = zeros(ComplexF64, 2L + Nobs)

    foreach_cubic_line(vac, terms3, k, grid, 2L) do a, b, w, u, x, T1, T2
        @. y[1:2L] = √18 * u
        for ν in 1:Nobs
            y[2L+ν] = pair_amplitude(words2[ν], T1, T2, a, b)
        end
        a ≤ L ? accum_binned!(decay, x, w / grid.npts, y) : accum_binned!(source, x, -w / grid.npts, y)
    end
    return (; decay, source)
end

"""
    OneLoop(swt::SpinWaveTheory; η, tol=0.01, loop_grid=nothing, vacuum=MagnonVacuum(swt))

The one-loop expansion about `vacuum`, with everything that is common to all
wavevectors: the mean-field, tadpole and anisotropy corrections to the quadratic
Hamiltonian, the corrections to the observables, and the resolution of the loop
integrals. Keywords are as in [`corrected_intensities`](@ref). The self-energy
at a wavevector is then [`SelfEnergy`](@ref).

Every mean field is a contraction in `vacuum`, taken on the loop grid of the
cubic self-energy, so that the Ward identity of each Goldstone mode cancels
static and dynamic shifts exactly, grid by grid, rather than to within the error
of two unrelated quadratures.
"""
struct OneLoop
    vacuum    :: MagnonVacuum
    η         :: Float64
    loop_grid :: NTuple{3, Int}
    # Binning error is O((Δ/η)²), so Δ/η = √tol contributes of order `tol`
    bin_width :: Float64
    terms3    :: Vector{BosonMonomial{3}}
    terms2    :: Vector{BosonMonomial{2}}
    δc        :: Matrix{ComplexF64}
end

function OneLoop(swt::SpinWaveTheory; η, tol=0.01, loop_grid=nothing, vacuum=MagnonVacuum(swt))
    check_corrections_supported(swt)
    vacuum.swt === swt || error("Vacuum must be built on the same `SpinWaveTheory`")
    η > 0 || error("Regulator `η` must be positive.")
    loop_grid = NTuple{3, Int}(@something loop_grid auto_loop_grid(vacuum, η, tol))

    # A negligible cubic vertex is dropped outright, e.g. collinear order in
    # dipole mode, so that everything it generates is exactly zero
    terms3 = cubic_monomials(swt)
    cubic_vertex_vanishes(swt, terms3) && empty!(terms3)

    terms4 = quartic_monomials(swt)
    g = contractions(vacuum, Iterators.flatten((terms3, terms4, observable_cubic_monomials(swt))), BZQuadrature(; grid=loop_grid))
    tad = isempty(terms3) ? nothing : tadpole(vacuum, terms3, g)
    terms2 = [mean_field(terms4, g).terms2
              isnothing(tad) ? BosonMonomial{2}[] : tad.terms2
              anisotropy_correction(swt).terms2]
    δc = observable_corrections(swt, isnothing(tad) ? nothing : tad.w, g)
    return OneLoop(vacuum, η, loop_grid, η * min(1/2, √tol), terms3, terms2, δc)
end

"""
    SelfEnergy(ol::OneLoop, q)

One-loop self-energy of the magnons at the wavevector `q` in RLU. Calling `Σ(z)`
at a complex frequency `z` returns the ``2L×2L`` Nambu matrix of the static and
cubic self-energies, counterterm included, in the quasi-particle basis of the
vacuum. The magnon Green's function of `dyson=:nambu` is then

    G(z) = inv(z * Ĩ - Diagonal(abs.(Σ.ε)) - Σ(z)),

with `Ĩ = Diagonal([ones(L); -ones(L)])` and `Σ.ε` the signed energies of the
vacuum. The field `Σ.T` is the Bogoliubov matrix of the vacuum at `q`, and `Σ.w`
the amplitudes of the observables, corrected at ``O(1/s)``, in the same basis.
Evaluating `Σ(z)` is cheap, so that e.g. a pole equation ``\\det G^{-1}(ω) = 0``
can be solved by root finding.
"""
struct SelfEnergy
    η      :: Float64
    ε      :: Vector{Float64}
    T      :: Matrix{ComplexF64}
    Σstat  :: Matrix{ComplexF64}
    w      :: Matrix{ComplexF64}
    decay  :: PairMeasure
    source :: PairMeasure
end

function SelfEnergy(ol::OneLoop, q)
    (; vacuum, loop_grid, bin_width) = ol
    (; swt) = vacuum
    (; sys) = swt
    L = nbands(swt)
    q_reshaped = to_reshaped_rlu(sys, q)
    q_global = orig_crystal(sys).recipvecs * q

    ws = BogoliubovWorkspace(L)
    ε = copy(vacuum_bogoliubov!(ws, zeros(ComplexF64, 2L, 2L), vacuum, q_reshaped))
    T = ws.T
    Σstat = static_self_energy_matrix(vacuum, ol.terms2, q_reshaped, T)

    u = zeros(ComplexF64, 2L, num_observables(swt.measure))
    set_swt_observable_vectors!(u, swt, q_reshaped, q_global)
    accum_observable_corrections!(u, swt, q_reshaped, q_global, ol.δc)
    w = T' * u

    grid = loop_wavevectors(loop_grid, q_reshaped)
    words2 = observable_pair_monomials(swt, q_reshaped, q_global)
    (; decay, source) = pair_measures(vacuum, ol.terms3, q_reshaped, grid; bin_width, words2)
    return SelfEnergy(ol.η, ε, T, Σstat, w, decay, source)
end

function (Σ::SelfEnergy)(z::Number)
    L = length(Σ.ε) ÷ 2
    return Σ.Σstat + cauchy_transform((Σ.decay, Σ.source), [z])[1:2L, 1:2L, 1]
end

# The self-energy Σstat + K frozen on the shell of its two legs, ½[K_mn(ε_m) +
# K_mn(ε_n)], plus the harmonic energies: a frequency-independent Nambu matrix in
# the quasi-particle basis. It reduces to K_nn(ε_n) on the diagonal and is
# Hermitian up to its absorptive part. The on-shell poles of `dyson=:on_shell`
# diagonalize its particle and hole blocks.
function on_shell_form(Σ::SelfEnergy)
    (; ε, η) = Σ
    L = length(ε) ÷ 2
    K = cauchy_transform((Σ.decay, Σ.source), ε .+ im*η)
    return Diagonal(abs.(ε)) + Σ.Σstat + [(K[m, n, m] + K[m, n, n]) / 2 for m in 1:2L, n in 1:2L]
end
