# Self-energy generated by the cubic vertex H₃. Entering at second order in
# perturbation theory, it shifts magnon energies at the same O(1/s) as the
# mean-field decoupling of H₄ in HartreeFock.jl and must be included alongside
# it, but unlike those corrections it is frequency dependent and complex, its
# imaginary part describing decay into the two-magnon continuum. Conventions are
# collected in Corrections.jl.
#
# Both channels there come from one contraction of H₃ at the momenta (𝐩, 𝐤-𝐩,
# -𝐤). The third slot carries the Nambu index L+n, creating the external magnon
# of band n at 𝐤; the first two carry indices a, b over the full Nambu space
# and so describe both internal lines at once. Writing ε_𝐩 for the 2L energies
# from `bogoliubov!`, an index a ≤ L selects a forward-propagating line of
# energy ε_𝐩[a] > 0 while a > L selects a backward one, of energy -ε_𝐩[a] > 0.
# The denominator ω - ε_𝐩[a] - ε_{𝐤-𝐩}[b] is therefore the decay denominator
# in the first case and the source denominator in the second, the only remaining
# distinction between the channels being the sign of their contribution. Lines
# propagating in opposite directions belong to no one-loop diagram.
#
# The overall factor of 18 arises as (1/2)·6², where 6 = 3! converts the
# slot-symmetrized `vertex!` output into the vertices Γ₁ and Γ₂ of
# Corrections.jl and the 1/2 counts the ways of attaching the internal lines.
#
# More generally the third slot may carry any Nambu index, giving a matrix
# self-energy whose off-diagonal elements within a block mix degenerate bands
# and correct spectral weights, and whose anomalous blocks describe the
# admixture of three magnons into the ground state. Writing m̄ = mod1(m+L, 2L)
# for the index that creates what m destroys,
#
#     Σ̂[m, m′] = τ₃[m] Σ_{a,b} ±18 conj(U[a, b, m̄]) U[a, b, m̄′] / (ω - ε_𝐩[a] - ε_{𝐤-𝐩}[b]).
#
# The asymmetry between the external legs is only apparent: the leading τ₃ makes
# τ₃Σ̂ Hermitian below the three-magnon threshold, as the Dyson equation
# requires. Both this structure and the factor of 18 are verified against the
# exact Nambu Green function of a cluster, whose 𝐪-independence lets one grid
# point integrate the loop exactly.

"""
    cubic_self_energy(swt::SpinWaveTheory, qpts, energies; η, grid)

Nambu matrix self-energy ``Σ̂_{mm′}(𝐪, ω)`` generated by the cubic term of the
Holstein-Primakoff expansion, evaluated at each of the given `energies`. Returns
an array of size `(2L, 2L, length(energies), size(qpts.qs)...)`, where `L =
nbands(swt)`, suitable for the Dyson equation that
[`corrected_intensities`](@ref) solves. See the single-argument method below for
the meaning of `η` and `grid`.
"""
function cubic_self_energy(swt::SpinWaveTheory, qpts, energies; η, grid)
    check_corrections_supported(swt)
    η > 0 || error("Broadening η must be positive")

    L = nbands(swt)
    qpts = convert(AbstractQPoints, qpts)
    terms3 = cubic_monomials(swt)

    ret = zeros(ComplexF64, 2L, 2L, length(energies), length(qpts.qs))
    for (iq, q) in enumerate(qpts.qs)
        k = to_reshaped_rlu(swt.sys, q)
        accum_cubic_self_energy!(view(ret, :, :, :, iq), swt, terms3, k, energies,
                                 loop_wavevectors(grid, k), η)
    end

    return reshape(ret, 2L, 2L, length(energies), size(qpts.qs)...)
end

"""
    cubic_self_energy(swt::SpinWaveTheory, qpts; η, grid)

On-shell self-energy of each magnon due to the cubic term of the
Holstein-Primakoff expansion, ``Σ_n(𝐪, ε_{𝐪n})``, where ``ε`` is the
[`dispersion`](@ref) of linear spin wave theory. Returns an array of complex
numbers with the same shape as `dispersion(swt, qpts)`. The real part is a
correction to the magnon energy of relative order ``1/s``, and should be added
to the mean-field corrections of [`hartree_fock_correction`](@ref) and
[`tadpole_correction`](@ref), which enter at the same order. Minus the imaginary
part is the half-width of the magnon peak, arising from decay into the
two-magnon continuum, which [`corrected_intensities`](@ref) resolves.

In `:dipole` and `:dipole_uncorrected` modes the self-energy vanishes
identically for a collinear magnetic structure. That is special to those modes,
and does not carry over to `:SUN`, where a single-ion level may decay into two
magnons of different flavors even when every dipole is parallel. It is otherwise
given by an integral over the magnetic Brillouin zone, which is performed on a
uniform `grid` of the given dimensions. Unlike the smooth integrands elsewhere
in this module, this one is singular wherever a magnon is degenerate with a pair
of magnons, so it is regularized by a small positive broadening `η`, and both
parameters must be converged together: `η` must exceed the grid spacing of the
energies being integrated, while remaining small compared to the linewidths
themselves.

The real part converges much more readily than the imaginary one, being a
principal value. Taking `η` below the energy grid spacing makes the imaginary
part far too small, because the sampled wavevectors then miss the resonant
surface entirely. A width that halves when `η` does is such an artifact.

Because only the diagonal part of the self-energy is returned, the result is
unreliable where two bands are degenerate.
"""
function cubic_self_energy(swt::SpinWaveTheory, qpts; η, grid)
    check_corrections_supported(swt)
    η > 0 || error("Broadening η must be positive")

    L = nbands(swt)
    qpts = convert(AbstractQPoints, qpts)
    terms3 = cubic_monomials(swt)
    disp = dispersion(swt, qpts)

    Σ = zeros(ComplexF64, 2L, 2L, L)
    ret = zeros(ComplexF64, L, length(qpts.qs))
    for (iq, q) in enumerate(qpts.qs)
        # Each band is evaluated at its own frequency, so the matrices for all L
        # frequencies are built and only their diagonals are kept.
        ωs = view(disp, :, iq)
        k = to_reshaped_rlu(swt.sys, q)
        accum_cubic_self_energy!(fill!(Σ, 0), swt, terms3, k, ωs, loop_wavevectors(grid, k), η)
        for n in 1:L
            ret[n, iq] = Σ[n, n, n]
        end
    end

    return reshape(ret, L, size(qpts.qs)...)
end

# Calls `f(a, b, w, u, x, T1, T2)` for each pair of internal magnon lines
# belonging to a one-loop diagram, line a carrying wavevector 𝐩 and line b
# carrying 𝐤-𝐩, with `w` the multiplicity `foreach_magnon_pair` supplies,
# averaged by the caller over the loop wavevectors of `grid`. Here `u[m] = U[a,
# b, nambu_conj(m, L)]` is the external leg of band m, for m up to `M`, and `x`
# is the pair energy. Both consumers below share this scaffolding, the external
# leg being delicate.
#
# That leg is independent of the loop wavevector. Indexing its slot by
# `nambu_conj(m, L)` asks for the operator adjoint to the mode m that the Dyson
# equation propagates, and an independent `bogoliubov!` at -k supplies that only
# up to a phase per band, nothing tying the eigenvectors of one call to those of
# another. Use instead the exact Nambu symmetry P H(k)ᵗ P = H(-k), where P is
# the index swap a ↦ nambu_conj(a, L), which follows from H22(k) = H11(-k)ᵗ and
# H12(k) = H12(-k)ᵗ. That makes T3 = P conj(T(k)) P para-unitary and a
# diagonalizer of H(-k), and its column `nambu_conj(m, L)` is by construction
# the adjoint of column m of T(k). A phase left free here would rescale the
# off-diagonal elements of Σ̂ relative to the mean fields and to the observables
# of Observables.jl, which are expressed in the columns of T(k) themselves;
# degenerate bands fare worse still, two calls being free to choose different
# bases within a degenerate block.
function foreach_cubic_line(f, swt::SpinWaveTheory, terms3, k, grid::LoopGrid, M)
    L = nbands(swt)
    U = zeros(ComplexF64, 2L, 2L, 2L)
    scratch = similar(U)
    u = zeros(ComplexF64, M)
    T3 = zeros(ComplexF64, 2L, 2L)

    let H = zeros(ComplexF64, 2L, 2L), T = zeros(ComplexF64, 2L, 2L)
        dynamical_matrix!(H, swt, k)
        bogoliubov!(T, H)
        for b in 1:2L, a in 1:2L
            T3[a, b] = conj(T[nambu_conj(a, L), nambu_conj(b, L)])
        end
    end

    foreach_magnon_pair(swt, k, grid) do p, w, T1, T2, ε1, ε2
        vertex!(U, terms3, (p, k - p, -k), (T1, T2, T3), scratch)
        for a in 1:2L, b in 1:2L
            # Internal lines must propagate in the same direction
            (a > L) == (b > L) || continue
            for m in 1:M
                u[m] = U[a, b, nambu_conj(m, L)]
            end
            f(a, b, w, u, ε1[a] + ε2[b], T1, T2)
        end
    end
end

# Accumulates into `Σ[:, :, iω]`, of size `2L×2L×length(ωs)`, the Nambu self-energy at
# wavevector `k` and frequency `ωs[iω]`, averaged over the wavevectors `ps` of the loop
# integral. `pair_measures` below evaluates the same integral by binning.
function accum_cubic_self_energy!(Σ, swt::SpinWaveTheory, terms3, k, ωs, grid::LoopGrid, η)
    L = nbands(swt)
    @assert size(Σ) == (2L, 2L, length(ωs))
    R = zeros(ComplexF64, 2L, 2L)

    foreach_cubic_line(swt, terms3, k, grid, 2L) do a, _b, w, u, x, _T1, _T2
        # The numerator is one rank-one matrix for all frequencies
        for m′ in 1:2L, m in 1:2L
            R[m, m′] = (a > L ? -18w : 18w) * (m > L ? -1 : 1) * conj(u[m]) * u[m′]
        end
        for (iω, ω) in enumerate(ωs)
            # Retarded frequencies lie just above the real axis, in both channels;
            # the source channel resonates only for ω < 0.
            c = 1 / (ω - x + im*η)
            for m′ in 1:2L, m in 1:2L
                Σ[m, m′, iω] += c * R[m, m′]
            end
        end
    end

    return Σ ./= grid.npts
end

# Binned measures of the auxiliary model of Corrections.jl, one per channel. Each
# internal line pair contributes the mass ±y y† at pair energy x, with
#
#     y = [√18 u; β],
#
# u the external legs over all 2L Nambu indices and β the amplitudes for the
# observables (words `words2`) to create the same pair directly. The decay
# channel has x > 0 and a plus sign; the source channel x < 0 and a minus sign.
# Their Cauchy transforms, summed, give the cubic self-energy in the `[1:2L,
# 1:2L]` block, in the orientation that contracts as w' G w.
function pair_measures(swt::SpinWaveTheory, terms3, k, grid::LoopGrid; bin_width, words2)
    L = nbands(swt)
    Nobs = length(words2)
    decay = PairMeasure(bin_width, 2L + Nobs)
    source = PairMeasure(bin_width, 2L + Nobs)
    y = zeros(ComplexF64, 2L + Nobs)

    foreach_cubic_line(swt, terms3, k, grid, 2L) do a, b, w, u, x, T1, T2
        @. y[1:2L] = √18 * u
        for ν in 1:Nobs
            y[2L+ν] = pair_amplitude(words2[ν], T1, T2, a, b)
        end
        a ≤ L ? accum_binned!(decay, x, w / grid.npts, y) : accum_binned!(source, x, -w / grid.npts, y)
    end
    return (; decay, source)
end
