# Self-energy generated by the cubic vertex H₃. Entering at second order in perturbation
# theory, it shifts magnon energies at the same O(1/s) as the mean-field decoupling of H₄
# in HartreeFock.jl and must be included alongside it, but unlike those corrections it is
# frequency dependent and complex, its imaginary part describing decay into the two-magnon
# continuum of TwoMagnon.jl. Conventions are collected in Corrections.jl.
#
# Both channels there come from one contraction of H₃ at the momenta (𝐩, 𝐤-𝐩, -𝐤). The third
# slot carries the Nambu index L+n, creating the external magnon of band n at 𝐤; the first
# two carry indices a, b over the full Nambu space and so describe both internal lines at
# once. Writing ε_𝐩 for the 2L energies from `bogoliubov!`, an index a ≤ L selects a
# forward-propagating line of energy ε_𝐩[a] > 0 while a > L selects a backward one, of
# energy -ε_𝐩[a] > 0. The denominator ω - ε_𝐩[a] - ε_{𝐤-𝐩}[b] is therefore the decay
# denominator in the first case and the source denominator in the second, the only remaining
# distinction between the channels being the sign of their contribution. Lines propagating
# in opposite directions belong to no one-loop diagram.
#
# The overall factor of 18 arises as (1/2)·6², where 6 = 3! converts the slot-symmetrized
# `vertex!` output into the vertices Γ₁ and Γ₂ of Corrections.jl and the 1/2 counts the ways
# of attaching the internal lines.
#
# More generally the third slot may carry any Nambu index, giving a matrix self-energy whose
# off-diagonal elements within a block mix degenerate bands and correct spectral weights,
# and whose anomalous blocks describe the admixture of three magnons into the ground state.
# Writing m̄ = mod1(m+L, 2L) for the index that creates what m destroys,
#
#     Σ̂[m, m′] = τ₃[m] Σ_{a,b} ±18 conj(U[a, b, m̄]) U[a, b, m̄′] / (ω - ε_𝐩[a] - ε_{𝐤-𝐩}[b]).
#
# The asymmetry between the external legs is only apparent: the leading τ₃ makes τ₃Σ̂
# Hermitian below the three-magnon threshold, as the Dyson equation requires. Both this
# structure and the factor of 18 are verified against the exact Nambu Green function of a
# dimer, whose 𝐪-independence lets one grid point integrate the loop exactly.
#
# The two channels behave very differently under resummation. In the particle block the
# decay channel is a sum of R/(ω - x + iη) with R = 18ū ū† ⪰ 0 and x real, so its imaginary
# part is negative semidefinite for every ω, which is what makes the resummed spectral
# function of CorrectedIntensities.jl positive. The source channel enters with the opposite
# sign and its own retarded regulator, giving a positive semidefinite imaginary part: an
# anti-damping. That is negligible off resonance, but the source denominator ω + |ε_𝐩[a]| +
# |ε_{𝐤-𝐩}[b]| becomes small as the internal pair energy vanishes, as it does at the
# ordering wavevector of an antiferromagnet, and resummation then turns the anti-damping
# into a spurious pole pushed up from negative frequency. This is a defect of the truncation
# rather than of the numerics; the remedy of Mourigal et al. (arXiv:1306.1231), implemented by
# `accum_frozen_source!` below, is to freeze the source channel at its on-shell frequency so
# that it acts as a static Hermitian shift. That discards only the channel's ω-slope, an
# O(1/s) contribution to the quasiparticle residue.

"""
    cubic_self_energy(swt::SpinWaveTheory, qpts, energies; η, grid)

Nambu matrix self-energy ``Σ̂_{mm′}(𝐪, ω)`` generated by the cubic term of the
Holstein-Primakoff expansion, evaluated at each of the given `energies`. Returns
an array of size `(2L, 2L, length(energies), size(qpts.qs)...)`, where `L =
nbands(swt)`, suitable for the Dyson equation that
[`intensities_corrected`](@ref) solves. See the single-argument method below for
the meaning of `η` and `grid`.
"""
function cubic_self_energy(swt::SpinWaveTheory, qpts, energies; η, grid)
    check_corrections_supported(swt)
    η > 0 || error("Broadening η must be positive")

    L = nbands(swt)
    qpts = convert(AbstractQPoints, qpts)
    terms3 = cubic_monomials(swt)

    ret = zeros(ComplexF64, 2L, 2L, length(energies), length(qpts.qs))
    for (iq, q) in enumerate(qpts.qs)
        k = to_reshaped_rlu(swt.sys, q)
        ps = loop_wavevectors(grid, k)
        accum_cubic_self_energy!(view(ret, :, :, :, iq), swt, terms3, k, energies, ps, η)
    end

    return reshape(ret, 2L, 2L, length(energies), size(qpts.qs)...)
end

"""
    cubic_self_energy(swt::SpinWaveTheory, qpts; η, grid)

On-shell self-energy of each magnon due to the cubic term of the
Holstein-Primakoff expansion, ``Σ_n(𝐪, ε_{𝐪n})``, where ``ε`` is the
[`dispersion`](@ref) of linear spin wave theory. Returns an array of complex
numbers with the same shape as `dispersion(swt, qpts)`. The real part is a
correction to the magnon energy of relative order ``1/s``, and should be added to
the mean-field corrections of [`hartree_fock_correction`](@ref) and
[`tadpole_correction`](@ref), which enter at the same order. Minus the imaginary
part is the half-width of the magnon peak, arising from decay into the
two-magnon continuum of [`intensities_two_magnon`](@ref).

The self-energy vanishes identically for a collinear magnetic structure. It is
otherwise given by an integral over the magnetic Brillouin zone, which is
performed on a uniform `grid` of the given dimensions. Unlike the smooth
integrands elsewhere in this module, this one is singular wherever a magnon is
degenerate with a pair of magnons, so it is regularized by a small positive
broadening `η`, and both parameters must be converged together: `η` must exceed
the grid spacing of the energies being integrated, while remaining small compared
to the linewidths themselves.

The real part converges much more readily than the imaginary one, being a
principal value. Taking `η` below the energy grid spacing makes the imaginary part
far too small, because the sampled wavevectors then miss the resonant surface
entirely. A width that halves when `η` does is such an artifact.

Because only the diagonal part of the self-energy is returned, the result is
unreliable where two bands are degenerate.
"""
function cubic_self_energy(swt::SpinWaveTheory, qpts; η, grid)
    check_corrections_supported(swt)
    η > 0 || error("Broadening η must be positive")

    L = nbands(swt)
    qpts = convert(AbstractQPoints, qpts)
    terms3 = cubic_monomials(swt)
    disp = dispersion(swt, qpts)

    Σ = zeros(ComplexF64, 2L, 2L, L)
    ret = zeros(ComplexF64, L, length(qpts.qs))
    for (iq, q) in enumerate(qpts.qs)
        # Each band is evaluated at its own frequency, so the matrices for all L
        # frequencies are built and only their diagonals are kept.
        ωs = view(disp, :, iq)
        k = to_reshaped_rlu(swt.sys, q)
        accum_cubic_self_energy!(fill!(Σ, 0), swt, terms3, k, ωs, loop_wavevectors(grid, k), η)
        for n in 1:L
            ret[n, iq] = Σ[n, n, n]
        end
    end

    return reshape(ret, L, size(qpts.qs)...)
end

# Calls `f(a, b, u, x, T1, T2)` for each pair of internal magnon lines belonging to a
# one-loop diagram, line a carrying wavevector 𝐩 and line b carrying 𝐤-𝐩, averaged by
# the caller over the loop wavevectors `ps`. Here `u[m] = U[a, b, nambu_conj(m, L)]` is
# the external leg of band m, for m up to `M`, and `x` is the pair energy. Both
# consumers below share this scaffolding, the external leg being delicate.
#
# That leg is independent of the loop wavevector. Indexing its slot by `nambu_conj(m, L)`
# asks for the operator adjoint to the mode m that the Dyson equation propagates, and an
# independent `bogoliubov!` at -k supplies that only up to a phase per band, nothing tying
# the eigenvectors of one call to those of another. Use instead the exact Nambu symmetry
# P H(k)ᵗ P = H(-k), where P is the index swap a ↦ nambu_conj(a, L), which follows from
# H22(k) = H11(-k)ᵗ and H12(k) = H12(-k)ᵗ. That makes T3 = P conj(T(k)) P para-unitary and a
# diagonalizer of H(-k), and its column `nambu_conj(m, L)` is by construction the adjoint of
# column m of T(k). A phase left free here would rescale the off-diagonal elements of Σ̂
# relative to the mean fields and to the observables of Observables.jl, which are expressed
# in the columns of T(k) themselves; degenerate bands fare worse still, two calls being free
# to choose different bases within a degenerate block.
function foreach_cubic_line(f, swt::SpinWaveTheory, terms3, k, ps, M)
    L = nbands(swt)
    U = zeros(ComplexF64, 2L, 2L, 2L)
    scratch = similar(U)
    u = zeros(ComplexF64, M)
    T3 = zeros(ComplexF64, 2L, 2L)

    let H = zeros(ComplexF64, 2L, 2L), T = zeros(ComplexF64, 2L, 2L)
        dynamical_matrix!(H, swt, k)
        bogoliubov!(T, H)
        for b in 1:2L, a in 1:2L
            T3[a, b] = conj(T[nambu_conj(a, L), nambu_conj(b, L)])
        end
    end

    foreach_magnon_pair(swt, k, ps) do p, T1, T2, ε1, ε2
        vertex!(U, terms3, (p, k - p, -k), (T1, T2, T3), scratch)
        for a in 1:2L, b in 1:2L
            # Internal lines must propagate in the same direction
            (a > L) == (b > L) || continue
            for m in 1:M
                u[m] = U[a, b, nambu_conj(m, L)]
            end
            f(a, b, u, ε1[a] + ε2[b], T1, T2)
        end
    end
end

# Frozen source channel, as described above: a static Hermitian shift, accumulated from
# the backward-propagating lines a > L. `source_freqs` is a real `L×L` matrix of
# nonnegative frequencies, one per pair of external bands. Because the denominator
# `source_freqs[m, m′] + |ε_𝐩[a]| + |ε_{𝐤-𝐩}[b]|` is strictly positive, the channel needs
# no regulator.
function accum_frozen_source!(Σsrc, source_freqs, u, x, L)
    for m′ in 1:L, m in 1:L
        Σsrc[m, m′] += -18 * conj(u[m]) * u[m′] / (source_freqs[m, m′] - x)
    end
end

# Accumulates into `Σ[:, :, iω]`, of size `2L×2L×length(ωs)`, the Nambu self-energy at
# wavevector `k` and frequency `ωs[iω]`, averaged over the wavevectors `ps` of the loop
# integral. Both channels are kept live; the frozen-source variant that the resummation
# of CorrectedIntensities.jl needs is `accum_pair_measure!` below, which evaluates the
# same integral by binning.
function accum_cubic_self_energy!(Σ, swt::SpinWaveTheory, terms3, k, ωs, ps, η)
    L = nbands(swt)
    @assert size(Σ) == (2L, 2L, length(ωs))
    R = zeros(ComplexF64, 2L, 2L)

    foreach_cubic_line(swt, terms3, k, ps, 2L) do a, _b, u, x, _T1, _T2
        # The numerator is one rank-one matrix for all frequencies
        for m′ in 1:2L, m in 1:2L
            R[m, m′] = (a > L ? -18 : 18) * (m > L ? -1 : 1) * conj(u[m]) * u[m′]
        end
        for (iω, ω) in enumerate(ωs)
            # Retarded frequencies lie just above the real axis, in both channels;
            # the source channel resonates only for ω < 0.
            c = 1 / (ω - x + im*η)
            for m′ in 1:2L, m in 1:2L
                Σ[m, m′, iω] += c * R[m, m′]
            end
        end
    end

    return Σ ./= length(ps)
end

# The same loop integral as above, evaluated by binning the decay measure in the pair
# energy rather than by a frequency loop inside the wavevector loop, as Corrections.jl
# describes. The cost then stops scaling with the number of frequencies, at the price of
# an O((bin_width/Γ)²) error. Grows `ρ` so that `ρ[b]` holds the masses at pair energy
# (b-1)*bin_width, and returns the frozen source shift; `pair_self_energy!` below turns
# the two into the self-energy at a set of frequencies.
#
# Supplying `pref`, the longitudinal observable prefactors of
# `pair_amplitude_prefactors!`, appends Nobs rows and columns carrying the amplitude for
# the same pair to be created directly by the observable, so that the blocks of `ρ` are
# the self-energy, the two-magnon continuum, and their interference. Only the decay
# channel contributes to them: a pair of real magnons is what the observable can create,
# and the source channel is frozen into a static shift.
function accum_pair_measure!(ρ, swt::SpinWaveTheory, terms3, k, ps; source_freqs, bin_width, pref=nothing)
    L = nbands(swt)
    # Rows of the blocked measure: the decay amplitude, and optionally the direct one
    Nobs = isnothing(pref) ? 0 : size(pref, 1)
    y = zeros(ComplexF64, L + Nobs)
    Σsrc = zeros(ComplexF64, L, L)

    foreach_cubic_line(swt, terms3, k, ps, L) do a, b, u, x, T1, T2
        if a > L
            return accum_frozen_source!(Σsrc, source_freqs, u, x, L)
        end
        # The measure is the rank-one y y† of Corrections.jl. Only the decay channel reaches
        # here, so every line is forward-propagating and the sign factors of
        # `accum_cubic_self_energy!` are unity. `y` is the amplitude to *create* the pair,
        # stored unconjugated throughout. Its leading block is thereby the transpose of the
        # `R` there, a distinction without a difference because that block is real
        # symmetric: it is a sum over a, b of conj(u)uᵗ together with its (b, a) partner.
        for m in 1:L
            y[m] = √18 * u[m]
        end
        for ν in 1:Nobs
            y[L+ν] = pair_amplitude(pref, T1, T2, a, b, ν, L)
        end
        (bin, f) = bin_index!(ρ, x, bin_width, () -> zeros(ComplexF64, L + Nobs, L + Nobs))
        for (bb, ww) in ((bin, 1 - f), (bin + 1, f))
            for m′ in eachindex(y), m in eachindex(y)
                ρ[bb][m, m′] += ww * y[m] * conj(y[m′])
            end
        end
    end

    foreach(m -> m ./= length(ps), ρ)
    return Σsrc ./ length(ps)
end

# Cauchy transform of the leading block of the binned measure, plus the frozen source
# shift: the self-energy that `accum_cubic_self_energy!` would return at the same `ωs`.
function pair_self_energy!(Σ, ρ, Σsrc, ωs, bin_width)
    L = size(Σ, 1)
    @assert size(Σ) == (L, L, length(ωs))
    for bin in eachindex(ρ)
        iszero(ρ[bin]) && continue
        for (iω, ω) in enumerate(ωs)
            c = 1 / (ω - (bin - 1) * bin_width)
            for m′ in 1:L, m in 1:L
                Σ[m, m′, iω] += c * ρ[bin][m, m′]
            end
        end
    end
    for iω in axes(Σ, 3)
        view(Σ, :, :, iω) .+= Σsrc
    end
    return Σ
end
