# Tadpole correction. Zero-point fluctuations shift the ordered structure away
# from the classical energy minimum, e.g. they change the canting angle of an
# antiferromagnet in a field. Conventions are collected in Corrections.jl and the
# monomial representation in Vertices.jl.
#
# The shift is realized as a uniform displacement of the Holstein-Primakoff
# bosons, b_{i,𝐫} → b_{i,𝐫} + v_i, rather than as a rotation of the classical
# dipoles. The two are equivalent, since ⟨S⁺_i⟩ = σ_i v_i tilts the moment away
# from the local ẑ axis, but the displacement is far better behaved numerically:
# away from a classical energy minimum the linear term H₁ no longer vanishes, and
# the quadratic form H₂ ceases to be positive definite near 𝐪 = 0, so
# `bogoliubov!` cannot even be applied there. Working with v keeps every
# calculation at the classical minimum, where LSWT is well defined.
#
# Substituting b → b + v produces a term linear in the bosons from H₂, and
# contracting two of the three legs of H₃ produces another (the tadpole itself).
# Requiring the total to vanish fixes v, which is of order s^(-1/2). The
# accompanying correction to H₂ comes from H₃ with a single leg replaced by v,
# and is of order s⁰, i.e. smaller than H₂ by 1/s, matching the mean-field
# correction from H₄.

# The three ways to contract two of three slots, listed as (p, q, r) where the
# pair (p, q) is contracted and r survives.
const CUBIC_PAIRINGS = ((1, 2, 3), (1, 3, 2), (2, 3, 1))

# Nambu components of the boson term generated by contracting two legs of each
# cubic monomial, ℓ[a] such that the operator is Σ_a ℓ[a] Σ_𝐫 O_a(𝐫). A cubic
# monomial reduces to a linear one as
#
#     O_p O_q O_r → ⟨O_p O_q⟩ O_r + ⟨O_p O_r⟩ O_q + ⟨O_q O_r⟩ O_p,
#
# with no constant to subtract because ⟨O_p O_q O_r⟩ vanishes in a Gaussian
# state. Cell offsets do not appear in the result: the surviving operator is
# summed over all cells, so only the offset difference within the contracted pair
# matters.
function tadpole_vector(terms::Vector{BosonMonomial{3}}, g, L)
    ℓ = zeros(ComplexF64, 2L)
    for (; c, as, ns) in terms, (p, q, r) in CUBIC_PAIRINGS
        ℓ[as[r]] += c * g(as[p], as[q], ns[q] - ns[p])
    end
    # Hermiticity of the underlying operator. The tolerance must be absolute as
    # well as relative, because symmetry can make ℓ vanish identically, leaving
    # only the noise of the momentum-space integration.
    @assert norm(ℓ[L+1:2L] - conj(ℓ[1:L])) < 1e-8 * max(norm(ℓ), 1)
    return ℓ
end

"""
    tadpole_correction(swt::SpinWaveTheory; opts...)

Computes the shift of the ordered magnetic structure caused by zero-point
fluctuations, which appears at relative order ``1/s``. An example is the change
in canting angle of an antiferromagnet in an applied field. Returns
`(; terms2, δE, dipoles)`, where `terms2` is a correction to the quadratic
Hamiltonian that can be passed to [`corrected_dispersion`](@ref), `δE` is a
correction to the energy per site, `dipoles` are the corrected classical dipoles
of the magnetic cell, and `v` is the underlying boson displacement, which
[`observable_corrections`](@ref) needs. The `dipoles` are rotated but not
shortened; the reduction of their magnitude is given by
[`magnetization_lswt_correction`](@ref).

Equivalently, `dipoles` minimizes the classical energy plus the zero-point energy
of [`energy_per_site_lswt_correction`](@ref), and `δE` is the resulting gain. The
correction is of the same size as the mean-field correction of
[`hartree_fock_correction`](@ref), so for a noncollinear structure the two should
be applied together. Restoring an exact Goldstone mode requires, in addition, the
self-energy generated by the cubic vertex, which enters at the same order.

A keyword argument `rtol`, `atol`, or `maxevals` is required to control the
accuracy of momentum-space integration.
"""
function tadpole_correction(swt::SpinWaveTheory; opts...)
    any(in(keys(opts)), (:rtol, :atol, :maxevals)) || error("Must specify one of `rtol`, `atol`, or `maxevals` to control momentum-space integration.")
    check_corrections_supported(swt)

    (; sys, data) = swt
    L = nbands(swt)
    terms3 = cubic_monomials(swt)
    ckeys = correlation_keys(L, terms3)
    gs = nambu_correlations(swt, ckeys, BosonMonomial{2}[]; opts...)
    ℓ = tadpole_vector(terms3, correlation_lookup(ckeys, gs, L), L)

    # An onsite anisotropy sources the displacement directly, at the same order. Its
    # one-boson word is proportional to the classical energy gradient, so like the
    # contractions above it vanishes at a classical minimum but not once tadpole
    # relaxation has moved the structure off one. In mode :dipole it vanishes
    # identically, because `rcs_factors` leaves the classical energy exact. See
    # `anisotropy_words`.
    for (; c, as) in anisotropy_monomials(swt, Val{1}())
        ℓ[as[1]] += c
    end

    # Packing v into the Nambu vector w, with w[i] = v_i and w[L+i] = conj(v_i),
    # the displacement of H₂ = Σ_𝐪 (1/2) x†_𝐪 H_𝐪 x_𝐪 contributes
    #
    #     (√N/2) (w† H₀ x₀ + x₀† H₀ w) = √N Σ_a (H₀ w)[ā] x₀[a],
    #
    # where the two halves coincide by the para-symmetry H₀[ā,b̄] = conj(H₀[a,b]).
    # Since Σ_𝐫 O_a(𝐫) = √N x₀[a], cancellation of the total linear term requires
    # (H₀ w)[ā] = -ℓ[a] for every a.
    #
    # H₀ is singular whenever the structure has a continuous degeneracy: a
    # Goldstone mode is a direction along which the structure may be rotated
    # freely, and by symmetry ℓ has no component along it. The pseudo-inverse
    # selects the minimum-norm solution, which is the one that leaves that
    # freedom unused. Its cutoff must also discard `swt.regularization`, which
    # would otherwise turn the Goldstone direction into a huge displacement.
    H = zeros(ComplexF64, 2L, 2L)
    dynamical_matrix!(H, swt, zero(Vec3))
    w = -pinv(H; rtol=1e-6) * [ℓ[nambu_conj(a, L)] for a in 1:2L]
    @assert norm(w[L+1:2L] - conj(w[1:L])) < 1e-8 * max(norm(w), 1)

    # Correction to H₂, from each cubic monomial with one leg displaced. Slot r
    # carries the displacement; slots (p, q) remain as operators, in order.
    terms2 = [BosonMonomial(c * w[as[r]], (as[p], as[q]), (ns[p], ns[q]))
              for (; c, as, ns) in terms3 for (p, q, r) in CUBIC_PAIRINGS]

    # Half the linear response, the usual energy gain of a displaced harmonic
    # system, since at the stationary point w† H₀ w = -Σ_a ℓ[a] w[a].
    δE = sum(ℓ .* w) / 2
    @assert abs(imag(δE)) < 1e-9 * max(abs(δE), 1)

    # In the local frame ⟨S⁺⟩ = σ ⟨b⟩ = σ v with σ = √(2s), so the moment tilts
    # away from ẑ by (Sˣ, Sʸ) = σ (Re v, Im v), to leading order in 1/s.
    dipoles = map(1:L) do i
        s = data.sqrtS[i]^2
        σ = √2 * data.sqrtS[i]
        return s * data.local_rotations[i] * normalize(Vec3(σ*real(w[i]), σ*imag(w[i]), s))
    end

    return (; terms2 = merge_monomials(terms2), δE = real(δE) / nsites(uncontracted_system(sys)), dipoles, v = w[1:L])
end
