struct FittingLoss
    f :: Function
    sys :: System
    labels :: Vector{Symbol}
    hp :: NamedTuple
end

function Base.show(io::IO, loss::FittingLoss)
    (; labels, hp) = loss
    hp_str = isempty(hp) ? "" : ", $hp"
    println(io, "FittingLoss($labels$hp_str)")
end

"""
    with_hyperparams(loss::FittingLoss, hp::NamedTuple)

Given a loss function generated by [`make_loss_fn`](@ref), returns a new loss
function where individual hyperparameters are overridden by the elements of
`hp`.
"""
function with_hyperparams(loss::FittingLoss, hp::NamedTuple)
    hp = Base.merge(loss.hp, hp) # If keys overlapping, 2nd arg wins
    return FittingLoss(loss.f, loss.sys, loss.labels, hp)
end

"""
    make_loss_fn(f, sys, labels; hp=NamedTuple())

Creates a `loss` function for use in model fitting. For example,

```julia
# Construct the loss function
loss = make_loss_fn(sys, labels) do sys
    minimize_energy!(sys)
    swt = SpinWaveTheory(sys; measure)
    res = intensities_bands(swt, path)
    return squared_error_bands(reference_energies, res)
end

# Measure goodness of fit for given parameter values
loss(vals)
```

Arbitrary code may appear in the callback `f` defined by the `do ... end` block.
[`SpinWaveTheory`](@ref) and [`SCGA`](@ref) calculators are convenient because
they are fast and deterministic.

The loss function is suitable for use in parameter optimization,

```julia
# Fit optimal parameters to about 6 digits of accuracy
import Optim
options = Optim.Options(g_tol=1e-6/energy_unit, show_trace=true)
fit = Optim.optimize(loss, values, Optim.NelderMead(), options)
fit.minimizer
```

Internally, each evaluation of `loss(vals)` performs these three steps,

```julia
sys2 = clone_system(sys)
set_params!(sys2, labels, vals)
f(sys2)
```

Furthermore, if `f` throws an instability error, then `loss` will catch it and
return `Inf`. This may happen, for example, if `f` attempts a spin wave
calculation on a magnetic state that is not energy-minimized for the new model
parameters.

Hyperparameters `hp` are passed as an optional second argument to `f`. Use
[`with_hyperparams`](@ref) to generate a new loss function with modified `hp`.
For example, one could anneal a smoothing parameter ϵ,

```julia
loss0 = make_loss_fn(sys, labels; hp=(; ϵ=0.0)) do sys, hp
    ... # Loss function involving hp.ϵ
end

x = guess
for ϵ in (1, 0.5, 0.25, 0.1)
    loss = with_hyperparams(loss0, (; ϵ))
    fit = Optim.optimize(loss, x, method, options)
    x = fit.minimizer
end
```

Automatic differentiation of the loss function is supported for certain
calculators (currently, just [`SCGA`](@ref)). This improves efficiency and
accuracy. See [Tutorial 10](@ref "10. Fitting to diffuse scattering data") for a
concrete example.
"""
function make_loss_fn(f, sys, labels; hp=NamedTuple())
    return FittingLoss(f, sys, labels, hp)
end

function (fl::FittingLoss)(vals)
    (; f, sys, labels, hp) = fl

    sys = clone_system(sys)
    set_params!(sys, labels, vals)
    sys.active_labels = labels
    try
        if applicable(f, sys, hp)
            return f(sys, hp)
        elseif applicable(f, sys)
            return f(sys)
        else
            error("Loss function not callable")
        end
    catch err
        (err isa InstabilityError) ? Inf : rethrow(err)
    end
end

function CRC.rrule(rc::CRC.RuleConfig, fl::FittingLoss, vals)
    (; f, sys, labels, hp) = fl

    sys = clone_system(sys)
    set_params!(sys, labels, vals)
    sys.active_labels = labels
    (L, f_pb) = try
        if applicable(f, sys, hp)
            CRC.rrule_via_ad(rc, f, sys, hp)
        elseif applicable(f, sys)
            CRC.rrule_via_ad(rc, f, sys)
        else
            error("Loss function not callable")
        end
    catch err
        (err isa InstabilityError) ? (Inf, nothing) : rethrow(err)
    end

    function pullback(ΔL)
        Δvals = if isinf(L)
            fill!(similar(vals), NaN)
        else
            _, Δsys = f_pb(ΔL)
            Δvals = CRC.unthunk(Δsys).vals
        end
        return (CRC.NoTangent(), Δvals)
    end

    return L, pullback
end


"""
    squared_error_fitted(x, y; weights=nothing, scale=false, shift=false)

Returns the normalized sum of squared errors,

```math
L = \\frac{1}{c} ∑_i w_i | y_i - (α x_i + β)|^2.
```

By default, ``α = 1`` and ``β = 0``. If `scale=true`, then determine ``α`` by
minimizing ``L``. If `shift=true`, then similarly optimize ``β``. Returns a
named tuple with fields `(; error, scale, shift)` for ``(L, α, β)``,
respectively.

Weights ``w_i`` must be nonnegative and default to one. Any `NaN` elements
``x_i`` or ``y_i`` will be interpreted as missing data and omitted from the sum.

The normalization factor ``c`` depends on the fitting options. In all cases, the
minimized ``L`` is symmetric in ``(x, y)`` and is of order one when ``x`` and
``y`` maximally disagree.

!!! tip "Closed-form expressions"

    Begin with some notation. Define the weighted inner product,

    ```math
        ⟨u, v⟩ = ∑_i w_i u_i^* v_i,
    ```

    and its associated norm ``\\|u\\|^2 = ⟨u, u⟩``. Define the weighted mean,

    ```math
    \\bar u = \\frac{∑_i w_i u_i}{∑_i w_i}.
    ```

    Define variables ``\\tilde u`` that optionally shift an input by its weighted
    mean: if `shift=true` then ``\\tilde u ≡ u - \\bar u`` , otherwise ``\\tilde u ≡
    u``.

    If optimized, the shift is ``β = \\bar y - α \\bar x``. Otherwise it is ``β =
    0``. Either way,

    ```math
    L = \\frac{1}{c} \\|\\tilde y - α \\tilde x\\|^2.
    ```

    There remain two possibilities for the final expression of ``L``.

    **Case 1, `scale=false`**: Here ``α = 1`` and we choose ``c`` so that,

    ```math
    L = \\frac{\\|\\tilde y - \\tilde x\\|^2}{\\|\\tilde x\\|^2 + \\|\\tilde y\\|^2}.
    ```

    **Case 2, `scale=true`**: Here the optimal scale factor is

    ```math
    α = \\frac{⟨\\tilde x, \\tilde y⟩}{\\|\\tilde x\\|^2}.
    ```

    We select ``c = ∑_i w_i \\|\\tilde y_i\\|^2`` so that substitution yields

    ```math
    L = 1 - \\frac{|⟨\\tilde x, \\tilde y⟩|^2}{\\|\\tilde x\\|^2\\,\\|\\tilde y\\|^2}.
    ```

    This may be understood as a cosine-squared loss. In case of complex inputs, note
    that the optimal ``α`` absorbs an arbitrary scale _and_ complex phase.
"""
function squared_error_fitted(x, y; weights=nothing, scale=false, shift=false)
    same_shape(x, y) || error("Mismatched input dimensions")
    (x, y) = flatten_to_vec.((x, y))
    ty = promote_type(eltype(x), eltype(y))
    rty = real(ty)

    w = if isnothing(weights)
        fill(one(rty), length(x))
    else
        same_shape(x, weights) || error("Mismatched weight dimensions")
        flatten_to_vec(weights)
    end

    # Shadow the inputs by their non-NaN subarrays
    inds = findall(i -> !isnan(x[i]) && !isnan(y[i]), eachindex(x))
    isempty(inds) && error("No valid data after removing NaNs")
    @views begin
        w = w[inds]
        x = x[inds]
        y = y[inds]
    end

    all(wi -> isreal(wi) && real(wi) >= 0, w) || error("Weights must be non-negative")

    # Raw weighted moments
    W = Diagonal(w)
    x2 = dot(x, W, x)
    y2 = dot(y, W, y)
    xy = dot(x, W, y)

    # Effective moments of x̃, ỹ
    x2t, y2t, xyt, xbar, ybar = if shift
        wsum = sum(w)
        iszero(wsum) && error("Sum of valid weights must be positive")

        xbar = dot(w, x) / wsum
        ybar = dot(w, y) / wsum

        (
            x2 - wsum * abs2(xbar),
            y2 - wsum * abs2(ybar),
            xy - wsum * conj(xbar) * ybar,
            xbar,
            ybar,
        )
    else
        (x2, y2, xy, zero(ty), zero(ty))
    end

    α, L = if scale
        if iszero(x2t) && iszero(y2t)
            (one(ty), zero(rty)) # Both centered inputs vanish; define cos² loss as 0
        elseif iszero(x2t) || iszero(y2t)
            (zero(ty), one(rty)) # One centered input vanishes; define cos² loss as 1
        else
            α = xyt / x2t
            L = real(1 - abs2(xyt) / (x2t * y2t))
            (α, L)
        end
    else
        α = one(ty)
        denom = x2t + y2t
        L = iszero(denom) ? zero(rty) : real((y2t + x2t - 2real(xyt)) / denom)
        (α, L)
    end

    L = clamp(L, 0, 1)
    β = shift ? ybar - α * xbar : zero(ty)
    return (; error=L, scale=α, shift=β)
end


"""
    squared_error(x, y; weights=nothing)

Normalized sum of squared errors, ``L = (1/c) \\sum_i w_i \\|y_i - x_i\\|^2``.
Weights ``w_i`` must be nonnegative and default to one.

The normalization factor is defined symmetrically, ``c = \\|x\\|^2 +
\\|y\\|^2``, involving the weighted norm,
```math
\\|u\\|^2 = \\sum_i w_i |u_i|^2.
```

Any NaN elements (``x_i`` or ``y_i``) will be interpreted as missing data and
omitted from the sum.

This function is a special case of [`squared_error_fitted`](@ref).
"""
squared_error(x, y; weights=nothing) = squared_error_fitted(x, y; weights).error


"""
wasserstein1_distance(p, q; γ=1.0)

Compute a Wasserstein-like distance between real-valued signals `p` and `q`,
uniformly sampled in one-dimension. This distance may be useful for comparing
energy-dependent spectral functions. For example, if ``p(E)`` and ``q(E)`` each
comprise a single spectral peak, then the returned Wasserstein distance is the
energy difference ``ΔE`` between peak centers divided by the full energy range.
By comparison, the naive [`squared_error`](@ref) between ``p(E)`` and ``q(E)``
would vanish uniformly for all nonzero ``ΔE``. The Wasserstein distance can
therefore be a powerful tool when fitting models to spectral data.

This function allows for _signed_ inputs. This can be important when processing
experimental data that, after background subtraction, may contain regions that
fluctuate about zero intensity. The returned distance measure properly accounts
for cancellations within these fluctuations.

For each input ``p`` (likewise ``q``) construct a cumulative signal ``P`` (or
``Q``) in two steps:

Step 1: Use the exponent ``γ ∈ (0, 1]`` to perform dynamic range compression
while preserving sign,

```math
\\tilde p_i = \\mathrm{sgn}(p_i) |p_i / c|^γ.
```

The default value ``γ = 1`` leaves the input signals unchanged. The coefficient
``c`` is arbitrary and cancels in the next step.

Step 2: Build the cumulative signal with normalization by total intensity
(assumed positive),

```math
P_i = \\frac{∑_{j=1}^i \\tilde p_j}{∑_{j=1}^n \\tilde p_j}.
```

Given cumulative signals ``P_i`` and ``Q_i``, this function returns their
``L_1`` distance,

```math
W_1 = \\frac{1}{n-1} ∑_{i=1}^{n-1} |P_i - Q_i|.
```

For nonnegative inputs, this is the usual Wasserstein distance scaled to the
range ``[0, 1]``. More generally, it is a transport-like measure.

If either `p[i]` or `q[i]` is `NaN`, then the elements at `i` are treated as
missing data and removed from both signals. Doing so effectively compresses any
gaps in the original grid.
"""
function wasserstein1_distance(
    p::AbstractVector{<: Real},
    q::AbstractVector{<: Real};
    γ::Real = 1.0,
)
    @assert length(p) == length(q)
    @assert 0 < γ ≤ 1

    ϕ(x) = isone(γ) ? x : copysign(abs(x)^γ, x)

    Mp = 0.0
    Mq = 0.0
    nvalid = 0

    foreach(p, q) do p_i, q_i
        if !isnan(p_i) && !isnan(q_i)
            nvalid += 1
            Mp += ϕ(p_i)
            Mq += ϕ(q_i)
        end
    end

    nvalid >= 2 || error("Input signals must have at least two valid points")
    (Mp > 0 && Mq > 0) || return Inf # Punish vanishing model prediction

    inv_Mp = 1 / Mp
    inv_Mq = 1 / Mq

    Δ = 0.0
    W₁ = 0.0
    started = false

    foreach(p, q) do p_i, q_i
        if !isnan(p_i) && !isnan(q_i)
            if started
                W₁ += abs(Δ)
            else
                started = true
            end
            Δ += ϕ(p_i) * inv_Mp - ϕ(q_i) * inv_Mq
        end
    end

    return W₁ / (nvalid - 1)
end


# Simple implementation of the Sinkhorn Gibbs algorithm for balanced optimal
# transport with entropic regularization. Should be essentially the same as
# OptimalTransport.sinkhorn.
function sinkhorn_simple(μ::AbstractVector, ν::AbstractVector, C::AbstractMatrix, ϵ::Real;
                         tol=1e-8, maxiter=10_000)
    M, N = size(C)
    length(μ) == M && length(ν) == N || error("Cost matrix C size mismatch")
    all(>(0), μ) || error("μ must be strictly positive")
    all(>(0), ν) || error("ν must be strictly positive")
    isapprox(sum(μ), sum(ν); rtol=1e-12, atol=1e-12) || error("sum(μ) and sum(ν) must match")

    tiny = eps(Float64)
    μmax = max(maximum(μ), tiny)
    νmax = max(maximum(ν), tiny)

    K = @. exp(-C / ϵ)
    u = ones(M)
    v = ones(N)
    resid1 = zeros(M)
    resid2 = zeros(N)

    KTu = zeros(N)
    Kv  = zeros(M)
    mul!(Kv, K, v)
    @. Kv = max(Kv, tiny)

    for iter in 1:maxiter
        @. u = μ / Kv

        mul!(KTu, K', u)
        @. KTu = max(KTu, tiny)
        @. v = ν / KTu

        mul!(Kv, K, v)
        @. Kv = max(Kv, tiny)

        @. resid1 = u * Kv  - μ
        @. resid2 = v * KTu - ν
        row_err = norm(resid1, Inf) / μmax
        col_err = norm(resid2, Inf) / νmax

        if max(row_err, col_err) ≤ tol
            break
        elseif iter == maxiter
            # Too noisy; breaks quickly with small ϵ
            # @warn "Non converged" row_err col_err
        end
    end

    γ = Diagonal(u) * K * Diagonal(v)
    return γ
end

# Use balanced optimal transport to smoothly assign labeled peaks E[k] to
# theoretical modes E0[m]. The assignment matrix γ is used to calculate a smooth
# squared error between all peaks and their closest modes.
function bands_transport_loss(E, E0, X0s; σ, ϵ, maxiter)
    M, K = length(E0), length(E)
    M >= K || error("$M SWT modes are insufficient to match $K labeled peaks")

    # M×K, cost matrix for matching mode m to peak k
    C_bare = [((E0[m] - E[k]) / σ)^2 for m in 1:M, k in 1:K]

    # A compression function for the cost matrix used in optimal transport.
    # Derived using x = log(exp(x)) = log(∑ₙ xⁿ/n!). The truncation below yields
    # f(x) = x + O(x⁴) at small x and f(x) ~ 3log(x) at large x.
    f(x) = log1p(x + x^2/2 + x^3/6)

    # Shift each column of the cost matrix so that its smallest value is 0. In
    # principle, the Sinkhorn algorithm is invariant to such shifts -- its
    # calculated occupations γ should depend only differences ΔC of column (or
    # row) elements. Note, however, that this shift becomes geometrically
    # meaningful once "compression" is performed in the next step.
    colmin = minimum(C_bare, dims=1)
    C_shift = C_bare .- colmin

    # The Sinkhorn algorithm depends on C through K = exp(-C) (for simplicity,
    # assume ϵ is scaled into C). If any matrix element of C is large (e.g.
    # -37), the corresponding occupation γ would be exponentially suppressed
    # (e.g. exp(-37) ≈ 1e-16, effectively 0 in Float64). To mitigate precision
    # issues, we compress the dynamical range of the cost matrix elements: C →
    # f(C). The function f is designed so that f(C) ≈ C at small C, yet grows
    # only logarithmically at large C. It is crucial to shift each column of C
    # prior to applying f(⋅). This maintains accuracy in ΔC for the smallest
    # elements of each column. In effect, for each peak k, C_compress[m, k]
    # respects the relative costs of the closest modes m, but is allowed to
    # underestimate costs of far away modes. For purposes of least-squares model
    # fitting, empirical tests indicate that the logarithmic growth of f(C) is
    # slow enough to tame numerics, but also fast enough to reasonably suppress
    # occupations γ at large C.
    C_compress = f.(C_shift)

    # M×(K+1) kernel for use in optimal transport. The final column is a "sink"
    # to absorb unused modes in the case of M > K. Its numerical value is
    # arbitrary (no effect on γ).
    C = hcat(C_compress, zeros(M))

    # Use the Sinkhorn algorithm to fractionally assign modes to peaks.
    μ = ones(M)              # mass for SWT modes
    ν = vcat(ones(K), M - K) # mass for labeled peaks (leftover goes to sink)
    γ = sinkhorn_simple(μ, ν, C, ϵ; maxiter)

    # Calculate the squared error for the smooth assignments γ. It is essential
    # to use C_bare because model fitting aims to minimize the _true_ squared
    # error.
    return dot(γ[:, 1:K], C_bare)
end

"""
    squared_error_bands_smooth(Es, res; σ)

Like `squared_error_bands` but uses entropy-regularized optimal transport to
smoothly assign labeled peak energies (`Es`) to spin wave modes (`res`). Entropy
regularization may be useful as part of an annealing procedure to search for a
globally optimal fit.

The energy parameter `σ` can be interpreted as an uncertainty in the `Es` data
and controls the amount of smoothing. This function coincides with
[`squared_error_bands`](@ref) in the limit of vanishing `σ`.
"""
function squared_error_bands_smooth(Es :: Vector{Vector{Float64}},
                                    res :: Sunny.BandIntensities;
                                    σ, ϵ=1.0, maxiter=1_000)
    nbands = size(res.disp, 1)
    E0s = eachcol(reshape(res.disp, nbands, :))
    X0s = eachcol(reshape(res.data, nbands, :))
    length(Es) == length(E0s) || error("Mismatch in bands vs data q-length ($(length(E0s))) ≠ $(length(Es))")
    σ > 0 || error("Energy uncertainty σ must be positive")
    ϵ > 0 || error("Entropic regularization ϵ must be positive")
    maxiter > 0 || error("Max iteration count must be positive")

    err = sum(bands_transport_loss.(Es, E0s, X0s; σ, ϵ, maxiter))
    return err / norm2(Es / σ)
end

"""
    squared_error_bands(Es, res)

Squared error between experimentally labeled intensity peaks (`Es`) and the
discrete energies of an [`intensities_bands`](@ref) calculation (`res`) for the
same ``𝐪``-points. Each element `Es[i]` is a list of labeled intensity peaks
for the `i`th ``𝐪``-point. Every labeled peak in `Es` will be assigned to some
spin wave band in `res`, but the converse is not true; any "extra" spin wave
bands do not contribute to the squared error.

The return value is normalized by the squared magnitude of `Es`. For example, if
the predicted modes are uniformly zero, then the return value is exactly 1.

Internally, this function uses the [Hungarian
algorithm](https://github.com/Gnimuc/Hungarian.jl) for optimal assignment of
modes to peaks.
"""
function squared_error_bands(Es :: Vector{Vector{Float64}}, res :: Sunny.BandIntensities)
    nbands = size(res.disp, 1)
    E0s = eachcol(reshape(res.disp, nbands, :))
    X0s = eachcol(reshape(res.data, nbands, :))
    length(Es) == length(E0s) || error("Mismatch in bands vs data q-length ($(length(E0s))) ≠ $(length(Es))")

    err = sum(map(Es, E0s, X0s) do E, E0, X0
        M, K = length(E0), length(E)
        M >= K || error("$M SWT modes are insufficient to match $K labeled peaks")
        C = [(E0[m] - E[k])^2 for m in 1:M, k in 1:K]
        hungarian(C)[2]
    end)

    return err / norm2(Es)
end


"""
    uncertainty_matrix(loss, x)

Returns the uncertainty matrix ``U = 2L(\\hat 𝐱) H(\\hat 𝐱)^{-1}`` at the loss
minimizer ``\\hat 𝐱``. Uses finite differences to estimate the Hessian ``H = ∇
∇ L``.

If ``L`` is a least-squares objective with a Gaussian noise model
interpretation, then ``U/ν`` estimates the covariance of fitted parameters
``\\hat 𝐱``. Here ``ν = N - p`` denotes the residual degrees of freedom: the
effective number of independent data points ``N`` minus the number of fitted
parameters ``p``. Statistical error bars follow, e.g.,

```math
\\mathrm{Std}(\\hat x_i) ≈ \\sqrt{U_{ii} / ν}.
```

Aside from statistics, the matrix ``U`` also admits a purely geometric
interpretation. Consider a quadratic expansion of ``L(𝐱)`` about its minimizer
``\\hat 𝐱``. Perturbations ``𝐱 - \\hat 𝐱`` that increase the loss by a factor
of 2 satisfy ``\\Delta 𝐱^T U^{-1} \\Delta 𝐱 ≈ 1``. Thus ``U^{-1}`` defines an
ellipsoid characterizing the shape and scale of the local loss basin.

We define the _**misfit tolerance**_ ``\\sqrt{𝐧^T U 𝐧 / 2}`` along any
normalized direction ``𝐧`` in parameter space. In particular, the misfit
tolerance for ``\\hat x_i`` is

```math
δ\\hat x_i = \\sqrt{U_{ii} / 2}.
```

Geometrically, ``δ\\hat x_i`` measures the scale over which the ``i``th
coordinate can vary before the loss grows by about 50%, while allowing
correlated adjustments of the remaining parameters. Although not itself a
statistical quantity, the misfit tolerance ``δ\\hat x_i`` nonetheless suggests a
scale for the admissable variation of inferred parameters.

!!! tip "Comparing statistical uncertainty and misfit tolerance"

    Observe that the misfit tolerance ``δ\\hat x_i`` has the same form as
    ``\\mathrm{Std}(\\hat x_i)``, but is significantly larger due to the missing
    ``ν^{-1/2}`` scaling factor.

    If noise in the data is the main limitation to overall fit quality, then
    ``\\mathrm{Std}(\\hat x_i)`` is the appropriate uncertainty measure. A signature
    of this regime is that the residuals ``y_i-f_i(\\hat 𝐱)`` show no obvious
    structure after accounting for known noise correlations.

    Often, however, statistical noise is effectively small relative to systematic
    modeling errors of various forms. For example, the fit could actually be limited
    by incompleteness of the Hamiltonian ansatz, imperfect global optimization of
    the Hamiltonian parameters, or intrinsic inaccuracies of the calculation method
    itself.

    When systematic errors are large, the misfit tolerance ``δ\\hat x_i`` may
    provide useful information. Rather than interpreting ``U / ν`` as a covariance
    matrix, the misfit tolerance uses ``U / 2`` to estimate a parameter range that
    limits loss function growth to about 50%. Whereas statistical error bars decay
    like ``ν^{-1/2} \\sim N^{-1/2}``, the misfit tolerance ``δ\\hat x_i`` will
    typically _not_ vanish in the large-data limit – even for a correctly specified
    model!

!!! tip "Derivation of the covariance estimator"

    Suppose the loss is a sum of squared errors with arbitrary scale ``c``,

    ```math
    L(𝐱) = \\frac{1}{c} χ^2(𝐱) = \\frac{1}{c} ∑_i \\frac{(y_i - f_i(𝐱))^2}{σ_i^2}.
    ```

    Assume a statistical model where ``y_i`` are sampled data, ``f_i(𝐱)`` are the
    corresponding model predictions, and ``σ_i`` are the standard deviations of
    independent Gaussian errors. Then, assuming a correctly specified model,
    ``χ^2/2`` is the negative log likelihood up to an irrelevant shift. The inverse
    Hessian of ``χ^2/2`` at the minimizer ``\\hat 𝐱`` estimates covariance. With
    our definition of ``H`` as the Hessian of ``L``, this is

    ```math
    \\mathrm{Cov}(\\hat 𝐱) ≈ \\frac{2}{c} H^{-1}.
    ```

    This expression could be used directly if ``c`` is known. Alternatively, to
    absorb an unknown noise scale ``c``, it is standard to rescale by the Pearson
    ``χ^2/ν`` statistic (overdispersion correction),

    ```math
    \\mathrm{Cov}(\\hat 𝐱) ≈ \\frac{2 χ^2}{c ν} H^{-1} = \\frac{1}{ν} 2 L H^{-1}.
    ```

    Recalling the definition ``U``, this establishes

    ```math
    \\mathrm{Cov}(\\hat 𝐱) ≈ U / ν.
    ```
"""
function uncertainty_matrix(loss, x; regularization=0.0, kwargs...)
    H = FiniteDiff.finite_difference_hessian(loss, x; kwargs...)
    return 2 * loss(x) * inv(H + regularization*I)
end


### Autodiff

Base.:+(a::SystemTangent, b::SystemTangent) = SystemTangent(a.vals .+ b.vals)
CRC.zero_tangent(t::SystemTangent) = SystemTangent(zero(t.vals))
CRC.unthunk(t::SystemTangent) = t

function CRC.ProjectTo(sys::System)
    n = length(sys.active_labels)
    function project(Δsys)
        Δsys = CRC.unthunk(Δsys)
        if Δsys isa CRC.NoTangent || Δsys isa CRC.AbstractZero
            return SystemTangent(zeros(n))
        elseif Δsys isa SystemTangent
            return Δsys
        else
            # if hasproperty(Δsys, :vals)
            #     return SystemTangent(getproperty(Δsys, :vals))
            # end
            error("Unsupported cotangent for System: $(typeof(Δsys))")
        end
    end
    return project
end

# Superceded by make_loss_fn. Kept here for historical interest.
#=
function with_params(sys::System, labels::Vector{Symbol}, vals::Vector{<: Real})
    sys = clone_system(sys)
    set_params!(sys, labels, vals)
    sys.active_labels = labels
    return sys
end
function CRC.rrule(::typeof(with_params), sys::System, labels, vals)
    sys2 = with_params(sys, labels, vals)
    proj_sys = CRC.ProjectTo(sys2)
    proj_vals = CRC.ProjectTo(vals)

    function pullback(Δsys2)
        Δsys2 = proj_sys(CRC.unthunk(Δsys2))
        return (CRC.NoTangent(), CRC.NoTangent(), CRC.NoTangent(), proj_vals(Δsys2.vals))
    end

    return sys2, pullback
end
=#
