struct FittingLoss
    f :: Function
    sys :: System
    labels :: Vector{Symbol}
    param_mapping :: Function
    hp :: NamedTuple
end

function Base.show(io::IO, loss::FittingLoss)
    (; labels, hp, param_mapping) = loss
    hp_str = isempty(hp) ? "" : ", $hp"
    map_str = (param_mapping === identity) ? "" : ", param_mapping=..."
    println(io, "FittingLoss($labels$hp_str$map_str)")
end

"""
    with_hyperparams(loss::FittingLoss, hp::NamedTuple)

Given a loss function generated by [`make_loss_fn`](@ref), returns a new loss
function where individual hyperparameters are overridden by the elements of
`hp`.
"""
function with_hyperparams(loss::FittingLoss, hp::NamedTuple)
    hp = Base.merge(loss.hp, hp) # If keys overlapping, 2nd arg wins
    return FittingLoss(loss.f, loss.sys, loss.labels, loss.param_mapping, hp)
end

"""
    make_loss_fn(f, sys, labels; param_mapping=identity, hp=NamedTuple())

Creates a `loss` function for use in model fitting. For example,

```julia
# Construct the loss function
loss = make_loss_fn(sys, labels) do sys
    minimize_energy!(sys)
    swt = SpinWaveTheory(sys; measure)
    res = intensities_bands(swt, path)
    return squared_error_bands(res, reference_energies)
end

# Measure goodness of fit for the labeled parameters x
loss(x)
```

Arbitrary code may appear in the callback `f` defined by the `do ... end` block.
[`SpinWaveTheory`](@ref) and [`SCGA`](@ref) calculations are common choices
because they are fast and deterministic.

The loss function is suitable for use in parameter optimization,

```julia
# Fit optimal parameters to about 6 digits of accuracy
import Optim
options = Optim.Options(g_tol=1e-6/energy_unit, show_trace=true)
fit = Optim.optimize(loss, values, Optim.NelderMead(), options)
fit.minimizer
```

Internally, each evaluation of `loss(x)` performs these steps,

```julia
sys2 = clone_system(sys)
set_params!(sys2, labels, param_mapping(x))
f(sys2)
```

Furthermore, if `f` throws an instability error, then `loss` will catch it and
return `Inf`. This may happen, for example, if `f` attempts a spin wave
calculation on a magnetic state that is not energy-minimized for the new model
parameters.

Hyperparameters `hp` are passed as an optional second argument to `f`. Use
[`with_hyperparams`](@ref) to generate a new loss function with modified `hp`.
For example, to perform annealing a regularization strength ϵ,

```julia
loss0 = make_loss_fn(sys, labels; hp=(; ϵ=0.0)) do sys, hp
    ... # Loss function involving hp.ϵ
end

x = guess
for ϵ in (1, 0.5, 0.25, 0.1)
    loss = with_hyperparams(loss0, (; ϵ))
    fit = Optim.optimize(loss, x, method, options)
    x = fit.minimizer
end
```

Automatic differentiation of the loss function is supported for certain
calculators (currently, just [`SCGA`](@ref)). This can improve efficiency and
accuracy. See [Tutorial 10](@ref "10. Fitting to diffuse scattering data") for a
concrete example.
"""
function make_loss_fn(f, sys, labels; param_mapping=identity, hp=NamedTuple())
    return FittingLoss(f, sys, labels, param_mapping, hp)
end

function (fl::FittingLoss)(x)
    (; f, sys, labels, param_mapping, hp) = fl

    sys = clone_system(sys)
    set_params!(sys, labels, param_mapping(x))
    sys.active_labels = labels
    try
        if applicable(f, sys, hp)
            return f(sys, hp)
        elseif applicable(f, sys)
            return f(sys)
        else
            error("Loss function not callable")
        end
    catch err
        (err isa InstabilityError) ? Inf : rethrow(err)
    end
end

function CRC.rrule(rc::CRC.RuleConfig, fl::FittingLoss, x)
    (; f, sys, labels, param_mapping, hp) = fl

    (vals, param_mapping_pb) = CRC.rrule_via_ad(rc, param_mapping, x)
    sys = clone_system(sys)
    set_params!(sys, labels, vals)
    sys.active_labels = labels
    (L, f_pb) = try
        if applicable(f, sys, hp)
            CRC.rrule_via_ad(rc, f, sys, hp)
        elseif applicable(f, sys)
            CRC.rrule_via_ad(rc, f, sys)
        else
            error("Loss function not callable")
        end
    catch err
        (err isa InstabilityError) ? (Inf, nothing) : rethrow(err)
    end

    function pullback(ΔL)
        Δx = if isinf(L)
            fill!(similar(x), NaN)
        else
            _, Δsys = f_pb(ΔL)
            Δvals = CRC.unthunk(Δsys).vals
            _, Δx = param_mapping_pb(Δvals)
            CRC.unthunk(Δx)
        end
        return (CRC.NoTangent(), Δx)
    end

    return L, pullback
end


# Returns weighted inner products ⟨x,x⟩, ⟨y,y⟩, ⟨x,y⟩
function squared_error_aux(x, y; weights)
    (x, y) = flatten_to_vec.((x, y))
    ty = promote_type(eltype(x), eltype(y))
    w = if isnothing(weights)
        fill(one(real(ty)), length(x))
    else
        flatten_to_vec(weights)
    end
    length(x) == length(y) == length(w) || error("Mismatched input sizes")
    all(@. real(w) >= 0 && iszero(imag(w))) || error("Weights must be non-negative")

    # This functional implementation is AD-friendly
    inds = findall(i -> !isnan(x[i]) && !isnan(y[i]), eachindex(x))
    @views begin
        x² = sum(@. w[inds] * abs2(x[inds]))           # |x|² ≡ ⟨x,x⟩
        y² = sum(@. w[inds] * abs2(y[inds]))           # |y|² ≡ ⟨y,y⟩
        xy = sum(@. w[inds] * conj(x[inds]) * y[inds]) # ⟨x,y⟩
    end
    return (; x², y², xy)
end

"""
    squared_error(x, y; weights=nothing)

Normalized sum of squared errors, ``L = (1/c) \\sum_i w_i |y_i - x_i|^2``.
Weights ``w_i`` must be nonnegative and default to one.

The normalization factor is defined symmetrically, ``c = |x|^2 + |y|^2``,
involving the weighted norm,
```math
|u|^2 = \\sum_i w_i |u_i|^2.
```

Any NaN elements (``x_i`` or ``y_i``) will be interpreted as missing data and
omitted from the sum.

See also [`squared_error_with_rescaling`](@ref).
"""
function squared_error(x, y; weights=nothing)
    (; x², y², xy) = squared_error_aux(x, y; weights)

    # |y - x|² / (|x|²+|y|²)
    return 1 - 2real(xy) / (x² + y²)
end

"""
    squared_error_with_rescaling(x, y; weights=nothing)

Normalized sum of squared errors, ``L = (1/c) \\min_α \\sum_i w_i |α y_i -
x_i|^2``, allowing for an arbitrary rescaling ``α`` of the ``y`` data. Weights
``w_i`` must be nonnegative and default to one. Returns a named tuple with
fields `(; error, rescaling)` that correspond to ``L`` and the optimal ``α``,
respectively.

The normalization factor,
```math
c = \\sum_i w_i |x_i|^2,
```
leads to a symmetry of ``L`` in its arguments ``(x, y)``.

Any NaN elements ``x_i`` or ``y_i`` will be interpreted as missing data and
omitted from the sum.

!!! tip "Relation to the cosine-squared loss"

    Introduce the weighted inner product,
    ```math
        ⟨u,v⟩ = \\sum_i w_i u_i^* v_i,
    ```
    and its associated norm, ``|u|^2 = ⟨u,u⟩``. In this notation, ``L = |α y - x|^2
    / |x|^2``. The optimal ``α`` is obtained by setting the Wirtinger derivative to
    zero, ``∂L/∂α^* = 0``, with solution
    ```math
        α = ⟨y, x⟩ / |y|².
    ```
    In case of complex inputs, this optimal ``α`` absorbs an arbitrary scale _and_
    complex phase. 

    Substitution yields the symmetric expression,
    ```math  
        L = 1 - |⟨x, y⟩|^2 / |x|^2 |y|^2.
    ```
    It may be interpreted as ``L = 1 - \\cos(θ)^2``, with ``θ`` the geometric angle
    between ``x`` and ``y`` in data-space.
"""
function squared_error_with_rescaling(x, y; weights=nothing)
    (; x², y², xy) = squared_error_aux(x, y; weights)

    # |α y - x|² / |x|² where α = ⟨y, x⟩ / |y|²
    error = 1 - abs2(xy) / (x² * y²)
    rescaling = conj(xy) / y²
    return (; error, rescaling)
end


# Simple implementation of the Sinkhorn Gibbs algorithm for balanced optimal
# transport with entropic regularization. Should be essentially the same as
# OptimalTransport.sinkhorn.
function sinkhorn_simple(μ::AbstractVector, ν::AbstractVector, C::AbstractMatrix, ϵ::Real;
                         tol=1e-8, maxiter=10_000)
    M, N = size(C)
    length(μ) == M && length(ν) == N || error("Cost matrix C size mismatch")
    all(>(0), μ) || error("μ must be strictly positive")
    all(>(0), ν) || error("ν must be strictly positive")
    isapprox(sum(μ), sum(ν); rtol=1e-12, atol=1e-12) || error("sum(μ) and sum(ν) must match")

    tiny = eps(Float64)
    μmax = max(maximum(μ), tiny)
    νmax = max(maximum(ν), tiny)

    K = @. exp(-C / ϵ)
    u = ones(M)
    v = ones(N)
    resid1 = zeros(M)
    resid2 = zeros(N)

    KTu = zeros(N)
    Kv  = zeros(M)
    mul!(Kv, K, v)
    @. Kv = max(Kv, tiny)

    for iter in 1:maxiter
        @. u = μ / Kv

        mul!(KTu, K', u)
        @. KTu = max(KTu, tiny)
        @. v = ν / KTu

        mul!(Kv, K, v)
        @. Kv = max(Kv, tiny)

        @. resid1 = u * Kv  - μ
        @. resid2 = v * KTu - ν
        row_err = norm(resid1, Inf) / μmax
        col_err = norm(resid2, Inf) / νmax

        if max(row_err, col_err) ≤ tol
            break
        elseif iter == maxiter
            # Too noisy; breaks quickly with small ϵ
            # @warn "Non converged" row_err col_err
        end
    end

    γ = Diagonal(u) * K * Diagonal(v)
    return γ
end

# Use balanced optimal transport to smoothly assign labeled peaks E[k] to
# theoretical modes E0[m]. The assignment matrix γ is used to calculate a smooth
# squared error between all peaks and their closest modes.
function bands_transport_loss(E0, X0s, E; σ, ϵ, maxiter)
    M, K = length(E0), length(E)
    M >= K || error("$M SWT modes are insufficient to match $K labeled peaks")

    # M×K, cost matrix for matching mode m to peak k
    C_bare = [((E0[m] - E[k]) / σ)^2 for m in 1:M, k in 1:K]

    # A compression function for the cost matrix used in optimal transport.
    # Derived using x = log(exp(x)) = log(∑ₙ xⁿ/n!). The truncation below yields
    # f(x) = x + O(x⁴) at small x and f(x) ~ 3log(x) at large x.
    f(x) = log1p(x + x^2/2 + x^3/6)

    # Shift each column of the cost matrix so that its smallest value is 0. In
    # principle, the Sinkhorn algorithm is invariant to such shifts -- its
    # calculated occupations γ should depend only differences ΔC of column (or
    # row) elements. Note, however, that this shift becomes geometrically
    # meaningful once "compression" is performed in the next step.
    colmin = minimum(C_bare, dims=1)
    C_shift = C_bare .- colmin

    # The Sinkhorn algorithm depends on C through K = exp(-C) (for simplicity,
    # assume ϵ is scaled into C). If any matrix element of C is large (e.g.
    # -37), the corresponding occupation γ would be exponentially suppressed
    # (e.g. exp(-37) ≈ 1e-16, effectively 0 in Float64). To mitigate precision
    # issues, we compress the dynamical range of the cost matrix elements: C →
    # f(C). The function f is designed so that f(C) ≈ C at small C, yet grows
    # only logarithmically at large C. It is crucial to shift each column of C
    # prior to applying f(⋅). This maintains accuracy in ΔC for the smallest
    # elements of each column. In effect, for each peak k, C_compress[m, k]
    # respects the relative costs of the closest modes m, but is allowed to
    # underestimate costs of far away modes. For purposes of least-squares model
    # fitting, empirical tests indicate that the logarithmic growth of f(C) is
    # slow enough to tame numerics, but also fast enough to reasonably suppress
    # occupations γ at large C.
    C_compress = f.(C_shift)

    # M×(K+1) kernel for use in optimal transport. The final column is a "sink"
    # to absorb unused modes in the case of M > K. Its numerical value is
    # arbitrary (no effect on γ).
    C = hcat(C_compress, zeros(M))

    # Use the Sinkhorn algorithm to fractionally assign modes to peaks.
    μ = ones(M)              # mass for SWT modes
    ν = vcat(ones(K), M - K) # mass for labeled peaks (leftover goes to sink)
    γ = sinkhorn_simple(μ, ν, C, ϵ; maxiter)

    # Calculate the squared error for the smooth assignments γ. It is essential
    # to use C_bare because model fitting aims to minimize the _true_ squared
    # error.
    return dot(γ[:, 1:K], C_bare)
end

"""
    squared_error_bands_smooth(res, Es; σ)

Like `squared_error_bands` but uses entropy-regularized optimal transport to
smoothly assign spin wave modes (`res`) to labeled peak energies (`Es`). Entropy
regularization may be useful as part of an annealing procedure to search for a
globally optimal fit.

The energy parameter `σ` can be interpreted as an uncertainty in the `Es` data
and controls the amount of smoothing. This function coincides with
[`squared_error_bands`](@ref) in the limit of vanishing `σ`.
"""
function squared_error_bands_smooth(res :: Sunny.BandIntensities,
                                    Es :: Vector{Vector{Float64}};
                                    σ, ϵ=1.0, maxiter=1_000)
    nbands = size(res.disp, 1)
    E0s = eachcol(reshape(res.disp, nbands, :))
    X0s = eachcol(reshape(res.data, nbands, :))
    length(Es) == length(E0s) || error("Mismatch in bands vs data q-length ($(length(E0s))) ≠ $(length(Es))")
    σ > 0 || error("Energy uncertainty σ must be positive")
    ϵ > 0 || error("Entropic regularization ϵ must be positive")
    maxiter > 0 || error("Max iteration count must be positive")

    err = sum(bands_transport_loss.(E0s, X0s, Es; σ, ϵ, maxiter))
    return err / norm2(Es / σ)
end

"""
    squared_error_bands(res, Es)

Squared error between the discrete band energies of an
[`intensities_bands`](@ref) calculation (`res`) and experimentally labeled
intensity peak energies (`Es`) for the same set of ``𝐪``-points. Each element
`Es[i]` is itself a list of labeled intensity peaks for the `i`th ``𝐪``-point.
Every labeled peak must match some spin wave band, but the converse may not be
true: Spin wave band without a labeled peak counterpart do not contribute to the
squared error.

The return value is normalized by the squared magnitude of `Es`. Specifically,
if the predicted mode are uniformly zero, then the return value is exactly 1.

Internally, this function uses the [Hungarian
algorithm](https://github.com/Gnimuc/Hungarian.jl) for optimal assignment of
modes to peaks.
"""
function squared_error_bands(res :: Sunny.BandIntensities,
                             Es :: Vector{Vector{Float64}})
    nbands = size(res.disp, 1)
    E0s = eachcol(reshape(res.disp, nbands, :))
    X0s = eachcol(reshape(res.data, nbands, :))
    length(Es) == length(E0s) || error("Mismatch in bands vs data q-length ($(length(E0s))) ≠ $(length(Es))")

    err = sum(map(E0s, X0s, Es) do E0, X0, E
        M, K = length(E0), length(E)
        M >= K || error("$M SWT modes are insufficient to match $K labeled peaks")
        C = [(E0[m] - E[k])^2 for m in 1:M, k in 1:K]
        hungarian(C)[2]
    end)

    return err / norm2(Es)
end


"""
    uncertainty_matrix(loss, x)

Returns an uncertainty matrix ``U`` that describes the slackness of the loss
function ``L`` at its minimizer ``x``. Specifically, ``U = L(x) H(x)^{-1}``
where ``H = ∂^2 L / ∂x ∂x`` is the Hessian matrix of second derivatives.

The quantity ``(U_{ii})^{1/2}`` can often be interpreted as uncertainty of the
fitted parameter ``x_i``. Similarly, ``(n^T U n)^{1/2}`` would be uncertainty in
the normalized direction ``n`` of parameter space.

There are situations where the above uncertainty estimates deviate strongly from
the true model error. For example, if the loss function is highly constraining
about the wrong minimum (e.g., due to model mispecification), then the
uncertainty estimate may be too low. Conversely, if the loss function does not
vanish for a perfect model fit (e.g., it is not a sum of squared errors), then
the uncertainty estimate may be too high.
"""
function uncertainty_matrix(loss, x; kwargs...)
    H = FiniteDiff.finite_difference_hessian(loss, x; kwargs...)
    return loss(x) * inv(H)
end


### Autodiff

Base.:+(a::SystemTangent, b::SystemTangent) = SystemTangent(a.vals .+ b.vals)
CRC.zero_tangent(t::SystemTangent) = SystemTangent(zero(t.vals))
CRC.unthunk(t::SystemTangent) = t

function CRC.ProjectTo(sys::System)
    n = length(sys.active_labels)
    function project(Δsys)
        Δsys = CRC.unthunk(Δsys)
        if Δsys isa CRC.NoTangent || Δsys isa CRC.AbstractZero
            return SystemTangent(zeros(n))
        elseif Δsys isa SystemTangent
            return Δsys
        else
            # if hasproperty(Δsys, :vals)
            #     return SystemTangent(getproperty(Δsys, :vals))
            # end
            error("Unsupported cotangent for System: $(typeof(Δsys))")
        end
    end
    return project
end

# Superceded by make_loss_fn. Kept here for historical interest.
#=
function with_params(sys::System, labels::Vector{Symbol}, vals::Vector{<: Real})
    sys = clone_system(sys)
    set_params!(sys, labels, vals)
    sys.active_labels = labels
    return sys
end
function CRC.rrule(::typeof(with_params), sys::System, labels, vals)
    sys2 = with_params(sys, labels, vals)
    proj_sys = CRC.ProjectTo(sys2)
    proj_vals = CRC.ProjectTo(vals)

    function pullback(Δsys2)
        Δsys2 = proj_sys(CRC.unthunk(Δsys2))
        return (CRC.NoTangent(), CRC.NoTangent(), CRC.NoTangent(), proj_vals(Δsys2.vals))
    end

    return sys2, pullback
end
=#
